pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t asad-app .'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker rm -f asad-container || true'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 5005:3000 --name asad-container asad-app'
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful'
        }
    }
}